Permissions boundary shouldn't be asked if supposed to skip interactive
openshift/rosa pull request #1028
Opened 2023-01-18 17:18 UTC by gdbranco

# What
Asks for permissions boundaries for operator roles during the cluster creation. If supplied consider we can skip interactive on creation of operator roles

# Why
Some automations may get interactive question during creation operator roles

2023-01-20 14:27 UTC, gdbranco commented
@vkareh PTAL

2023-01-20 20:54 UTC, vkareh requested changes
I don't like this. If this breaks automation, just add the `&& !skipInteractive` condition. but do not duplicate the interactive prompt. We already capture the `--permissions-boundary` flag and forward it. That should be sufficient for automation. In fact, if the interactive prompt shows during cluster creation, automation has already been broken.

2023-01-20 23:33 UTC, gdbranco commented
> I don't like this. If this breaks automation, just add the `&& !skipInteractive` condition. but do not duplicate the interactive prompt. We already capture the `--permissions-boundary` flag and forward it. That should be sufficient for automation. In fact, if the interactive prompt shows during cluster creation, automation has already been broken.

skipinteractive is indeed needed for the automation. Adding it as part of cluster creation just adds an optional param though, would breaking the automation be due to a user supplying entries individually during interactive mode instead of using the param? Not sure if I followed

2023-01-20 23:50 UTC, vkareh commented
My point is that we already allow the flag to be set AND we also have interactive flow for the flag in the second command.

We shouldn't duplicate the interactive prompt, so either you set the skipInteractive flag or you don't, and the prompt is shown based on that.

Does that make sense? Also, I may have the flow wrong, to be honest :P

On January 20, 2023 6:34:01 p.m. EST, Guilherme Branco ***@***.***> wrote:
>> I don't like this. If this breaks automation, just add the `&& !skipInteractive` condition. but do not duplicate the interactive prompt. We already capture the `--permissions-boundary` flag and forward it. That should be sufficient for automation. In fact, if the interactive prompt shows during cluster creation, automation has already been broken.
>
>skipinteractive is indeed needed for the automation. Adding it as part of cluster creation just adds an optional param though, would breaking the automation be due to a user supplying entries individually during interactive mode instead of using the param? Not sure if I followed
>
>

2023-01-23 11:07 UTC, gdbranco commented
> My point is that we already allow the flag to be set AND we also have interactive flow for the flag in the second command. We shouldn't duplicate the interactive prompt, so either you set the skipInteractive flag or you don't, and the prompt is shown based on that. Does that make sense? Also, I may have the flow wrong, to be honest :P
> […](#)
> On January 20, 2023 6:34:01 p.m. EST, Guilherme Branco ***@***.***> wrote: > I don't like this. If this breaks automation, just add the `&& !skipInteractive` condition. but do not duplicate the interactive prompt. We already capture the `--permissions-boundary` flag and forward it. That should be sufficient for automation. In fact, if the interactive prompt shows during cluster creation, automation has already been broken. skipinteractive is indeed needed for the automation. Adding it as part of cluster creation just adds an optional param though, would breaking the automation be due to a user supplying entries individually during interactive mode instead of using the param? Not sure if I followed

Makes sense, changed so that we only skip question in create operator roles if is called from another command

2023-01-25 15:11 UTC, vkareh commented
/lgtm

2023-01-25 15:29 UTC, merged