OCM-114005 | fix: A few bug fixes for registry config
openshift/rosa pull request #2500
Opened 2024-09-24 19:01 UTC by chenz4027

2024-09-24 19:02 UTC, chenz4027 commented on cmd/edit/cluster/cmd.go
> +		prompt := "Enabling cluster registry will cause rollout accross all nodepools. Do you want to proceed?"
Current prompt looks like following.

If params set:
```
rosa git:(OCM-11405) ✗ ./rosa edit cluster -c magchen-hcp --registry-config-platform-allowlist 2e0auar98h9ajmd6ndlmlqr5lsibkm4v

? Enabling cluster registry will cause rollout accross all nodepools. Do you want to proceed? Yes
I: Updated cluster 'magchen-hcp'
```

Interactive mode:
```
➜  rosa git:(OCM-11405) ✗ ./rosa edit cluster -c magchen-hcp -i                                                                  
I: Interactive mode enabled.
Any optional fields can be ignored and will not be updated.
? Private cluster, check this command's help for possible impacts: No
? Disable Workload monitoring: No
? Update cluster-wide proxy: No
? Update additional trust bundle: No
? Update additional allowed principals: No
? Enable audit log forwarding to AWS CloudWatch: No
? Allowed Registries: abc.com
? Insecure Registries: insecure.com
? Allowed Registries For Import: quay.io:true
? Registry Additional Trusted CA (optional): 
? Enabling cluster registry will cause rollout accross all nodepools. Do you want to proceed? Yes
? Enable cluster deletion protection: No
I: Updated cluster 'magchen-hcp'
```

2024-09-24 19:16 UTC, chenz4027 commented on cmd/edit/cluster/cmd.go
> +		prompt := "Enabling cluster registry will cause rollout accross all nodepools. Do you want to proceed?"
I miss spelled across to "accross", now it's fixed.

2024-09-25 13:14 UTC, gdbranco commented
/lgtm
/approve

2024-09-25 13:35 UTC, gdbranco commented
/hold

2024-09-25 14:37 UTC, chenz4027 commented on cmd/edit/cluster/cmd.go
> +		prompt := "Enabling cluster registry will cause rollout across all nodepools. Do you want to proceed?"
Good catch @andreadecorte !

2024-09-25 14:52 UTC, arendej requested changes

2024-09-25 14:52 UTC, arendej commented on cmd/edit/cluster/cmd.go
> +		prompt := "Enabling cluster registry will cause rollout across all nodepools. Do you want to proceed?"
change text to:

`Warning: Enabling or editing the cluster registry configuration will cause a rollout across all machinepools (all machinepool nodes will be recreated, following pod draining from each node). Do you want to proceed?`

2024-09-25 14:52 UTC, arendej commented on cmd/edit/cluster/cmd.go
> +			r.Reporter.Warnf("You opted out from enabling a cluster with registry config.")
change text to:
`You have not changed any registry configuration -- exiting.`

2024-09-25 14:52 UTC, arendej commented on pkg/clusterregistryconfig/flags.go
> +				return nil, fmt.Errorf("Expected a valid value for allowed registries: %s", err)
what is a valid value? can we show an example or explain if it's a comma separated string?

2024-09-25 14:52 UTC, arendej commented on pkg/clusterregistryconfig/flags.go
> +				return nil, fmt.Errorf("Expected a valid value for blocked registries: %s", err)
same comment as for allowed registries above

2024-09-25 15:59 UTC, chenz4027 commented
Updated the text, I combined the suggestions from both @andreadecorte and @arendej . Would you mind taking another look?

2024-09-25 18:14 UTC, andreadecorte commented on cmd/edit/cluster/cmd.go
> +		prompt := "Enabling cluster registry will cause rollout across all nodepools. Do you want to proceed?"
```
./rosa edit cluster -c ad-loc7 --registry-config-insecure-registries insecure.io,insecure2.io,insecure3.io
? Changing any registry related parameter will trigger a rollout across all machinepools (all machinepool nodes will be recreated, following pod draining from each node). Do you want to proceed? (y/N)
W: You have not changed any registry configuration -- exiting.
```
looks good now

2024-09-25 18:14 UTC, andreadecorte commented
/approve

2024-09-25 21:02 UTC, arendej approved these changes
thanks for the changes

2024-09-26 10:07 UTC, gdbranco commented
/unhold
/lgtm

2024-09-26 10:07 UTC, gdbranco commented
/cherry-pick release_1.2.46

2024-09-26 10:47 UTC, merged