fix for - Not able to remove or add a new cluster-admin in rosa cli
openshift/rosa pull request #790
Opened 2022-07-18 08:34 UTC by zvikorn

fix for - Can't create temporary admin user for ROSA cluster

Signed-off-by: Tzvika Avni <tavni@redhat.com>

SDA-6170
SDA-6106

2022-07-18 08:36 UTC, zvikorn commented
@pvasant PTAL

2022-07-18 12:27 UTC, pvasant commented
@zgalor @oriAdler  PTAL

2022-07-18 12:39 UTC, samira-barouti reviewed
A few questions/comments

2022-07-18 12:39 UTC, samira-barouti commented on cmd/dlt/admin/cmd.go
> +			r.Reporter.Errorf("Failed to delete '%s' user from clster-admins groups	 of cluster '%s': %s",
typo:
clstr -> cluster

2022-07-18 15:40 UTC, pvasant commented
/ok-to-test

2022-07-18 18:26 UTC, samira-barouti requested changes

2022-07-18 18:27 UTC, samira-barouti commented
@zvikorn I left one comment on the name of the constant. Other than that, it is GTG.

2022-07-19 06:28 UTC, zvikorn commented on cmd/grant/user/cmd.go
> +	if username == idp.ClusterAdminUsername {
this one as to be exposed as other packages are using it

2022-07-19 06:29 UTC, zgalor commented
/lgtm

2022-07-19 06:34 UTC, merged